name: Python Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Replace with your Python version

    - name: Install PyInstaller
      run: |
        python -m pip install pyinstaller

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile /Next-mover/next_clicker.py  # Replace with your actual script name

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v1.0.0  # Replace with your desired release tag
        release_name: Release v1.0.0  # Replace with your desired release name
        body: |
          Changes in this release:
          - Describe your changes here

    - name: Upload release artifact
      uses: actions/upload-artifact@v2
      with:
        name: release-artifact
        path: dist  # Change to the actual path where PyInstaller puts the executable

    - name: Deploy
      uses: actions/deploy@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        file: release-artifact
        release_id: ${{ steps.create_release.outputs.id }}


name: Python Pre-Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Use Python 3.11

    - name: Install PyInstaller
      run: |
        python -m pip install pyinstaller

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile /Next-mover/next_clicker.py  # Replace with your actual script name

    - name: Set tag and release names
      run: |
        echo "::set-env name=TAG_NAME::$(git log -1 --format=%h)"
        echo "::set-env name=RELEASE_NAME::Release-$(date +'%Y%m%d%H%M%S')"

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: ${{ env.RELEASE_NAME }}
        prerelease: true
        body: |
          Changes in this release:
          - Describe your changes here

    - name: Upload release artifact
      uses: actions/upload-artifact@v2
      with:
        name: release-artifact
        path: dist  # Change to the actual path where PyInstaller puts the executable

    - name: Deploy
      uses: actions/deploy@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        file: release-artifact
        release_id: ${{ steps.create_release.outputs.id }}

